"""Inicial

Revision ID: b0f443e84570
Revises: 
Create Date: 2025-06-15 17:35:02.729394

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0f443e84570'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome_usuario', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('senha_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_usuario_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_usuario_nome_usuario'), ['nome_usuario'], unique=True)

    op.create_table('produto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=140), nullable=True),
    sa.Column('marca', sa.String(length=100), nullable=True),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('categoria', sa.String(length=50), nullable=True),
    sa.Column('imagem', sa.String(length=120), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], name='fk_produto_usuario'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('receita',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=100), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=False),
    sa.Column('ingredientes', sa.Text(), nullable=False),
    sa.Column('instrucoes', sa.Text(), nullable=False),
    sa.Column('tags', sa.String(length=200), nullable=True),
    sa.Column('imagem', sa.String(length=200), nullable=True),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], name='fk_receita_usuario'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('receita', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_receita_data_criacao'), ['data_criacao'], unique=False)

    op.create_table('avaliacao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nota', sa.Integer(), nullable=True),
    sa.Column('comentario', sa.Text(), nullable=True),
    sa.Column('data_avaliacao', sa.DateTime(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('receita_id', sa.Integer(), nullable=True),
    sa.Column('produto_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['produto_id'], ['produto.id'], name='fk_avaliacao_produto'),
    sa.ForeignKeyConstraint(['receita_id'], ['receita.id'], name='fk_avaliacao_receita'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], name='fk_avaliacao_usuario'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('avaliacao', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_avaliacao_data_avaliacao'), ['data_avaliacao'], unique=False)

    op.create_table('favorito',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('receita_id', sa.Integer(), nullable=True),
    sa.Column('produto_id', sa.Integer(), nullable=True),
    sa.Column('data_favorito', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['produto_id'], ['produto.id'], name='fk_favorito_produto'),
    sa.ForeignKeyConstraint(['receita_id'], ['receita.id'], name='fk_favorito_receita'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], name='fk_favorito_usuario'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('favorito', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_favorito_data_favorito'), ['data_favorito'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorito', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_favorito_data_favorito'))

    op.drop_table('favorito')
    with op.batch_alter_table('avaliacao', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_avaliacao_data_avaliacao'))

    op.drop_table('avaliacao')
    with op.batch_alter_table('receita', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_receita_data_criacao'))

    op.drop_table('receita')
    op.drop_table('produto')
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usuario_nome_usuario'))
        batch_op.drop_index(batch_op.f('ix_usuario_email'))

    op.drop_table('usuario')
    # ### end Alembic commands ###
